pokeTypes = {
			 1 : ["grass","poison"],
			 2 : ["grass","poison"],
			 3 : ["grass","poison"],
			 4 : ["fire","none"],
			 5 : ["fire","none"],
			 6 : ["fire","flying"],
			 7 : ["water","none"],
			 8 : ["water","none"],
			 9 : ["water","none"],
			 10 : ["bug","none"],
			 11 : ["bug","none"],
			 12 : ["bug","flying"],
			 13 : ["bug","poison"],
			 14 : ["bug","poison"],
			 15 : ["bug","poison"],
			 16 : ["normal","flying"],
			 17 : ["normal","flying"],
			 18 : ["normal","flying"],
			 19 : ["normal","none"],
			 20 : ["normal","none"],
			 21 : ["normal","flying"],
			 22 : ["normal","flying"],
			 23 : ["poison","none"],
			 24 : ["poison","none"],
			 25 : ["electric","none"],
			 26 : ["electric","none"],
			 27 : ["ground","none"],
			 28 : ["ground","none"],
			 29 : ["poison","none"],
			 30 : ["poison","none"],
			 31 : ["poison","ground"],
			 32 : ["poison","none"],
			 33 : ["poison","none"],
			 34 : ["poison","ground"],
			 35 : ["fairy","none"],
			 36 : ["fairy","none"],
			 37 : ["fire","none"],
			 38 : ["fire","none"],
			 39 : ["normal","fairy"],
			 40 : ["normal","fairy"],
			 41 : ["poison","flying"],
			 42 : ["poison","flying"],
			 43 : ["grass","poison"],
			 44 : ["grass","poison"],
			 45 : ["grass","poison"],
			 46 : ["bug","grass"],
			 47 : ["bug","grass"],
			 48 : ["bug","poison"],
			 49 : ["bug","poison"],
			 50 : ["ground","none"],
			 51 : ["ground","none"],
			 52 : ["normal","none"],
			 53 : ["normal","none"],
			 54 : ["water","none"],
			 55 : ["water","none"],
			 56 : ["fighting","none"],
			 57 : ["fighting","none"],
			 58 : ["fire","none"],
			 59 : ["fire","none"],
			 60 : ["water","none"],
			 61 : ["water","none"],
			 62 : ["water","fighting"],
			 63 : ["psychic","none"],
			 64 : ["psychic","none"],
			 65 : ["psychic","none"],
			 66 : ["fighting","none"],
			 67 : ["fighting","none"],
			 68 : ["fighting","none"],
			 69 : ["grass","poison"],
			 70 : ["grass","poison"],
			 71 : ["grass","poison"],
			 72 : ["water","poison"],
			 73 : ["water","poison"],
			 74 : ["rock","ground"],
			 75 : ["rock","ground"],
			 76 : ["rock","ground"],
			 77 : ["fire","none"],
			 78 : ["fire","none"],
			 79 : ["water","psychic"],
			 80 : ["water","psychic"],
			 81 : ["electric","steel"],
			 82 : ["electric","steel"],
			 83 : ["normal","flying"],
			 84 : ["normal","flying"],
			 85 : ["normal","flying"],
			 86 : ["water","none"],
			 87 : ["water","ice"],
			 88 : ["poison","none"],
			 89 : ["poison","none"],
			 90 : ["water","none"],
			 91 : ["water","ice"],
			 92 : ["ghost","poison"],
			 93 : ["ghost","poison"],
			 94 : ["ghost","poison"],
			 95 : ["rock","ground"],
			 96 : ["psychic","none"],
			 97 : ["psychic","none"],
			 98 : ["water","none"],
			 99 : ["water","none"],
			 100 : ["electric","none"],
			 101 : ["electric","none"]
			 }
			 
moveTypes = {
			"10,000,000 Volt Thunderbolt" : "electric",
			 "Absorb" : "grass",
			 "Accelerock" : "rock",
			 "Acid" : "poison",
			 "Acid Armor" : "none",
			 "Acid Downpour" : "poison",
			 "Acid Spray" : "poison",
			 "Acrobatics" : "flying",
			 "Acupressure" : "none",
			 "Aerial Ace" : "flying",
			 "Aeroblast" : "flying",
			 "After You" : "none",
			 "Agility" : "none",
			 "Air Cutter" : "flying",
			 "Air Slash" : "flying",
			 "All-Out Pummeling" : "fighting",
			 "Ally Switch" : "none",
			 "Amnesia" : "none",
			 "Anchor Shot" : "steel",
			 "Ancient Power" : "rock",
			 "Aqua Jet" : "water",
			 "Aqua Ring" : "none",
			 "Aqua Tail" : "water",
			 "Arm Thrust" : "fighting",
			 "Aromatherapy" : "none",
			 "Aromatic Mist" : "none",
			 "Assist" : "none",
			 "Assurance" : "dark",
			 "Astonish" : "ghost",
			 "Attack Order" : "bug",
			 "Attract" : "none",
			 "Aura Sphere" : "fighting",
			 "Aurora Beam" : "ice",
			 "Autotomize" : "none",
			 "Avalanche" : "ice",
			 "Baby-Doll Eyes" : "none",
			 "Baneful Bunker" : "none",
			 "Barrage" : "normal",
			 "Barrier" : "none",
			 "Baton Pass" : "none",
			 "Beak Blast" : "flying",
			 "Beat Up" : "dark",
			 "Belch" : "poison",
			 "Belly Drum" : "none",
			 "Bestow" : "none",
			 "Bide" : "normal",
			 "Bind" : "normal",
			 "Bite" : "dark",
			 "Blast Burn" : "fire",
			 "Blaze Kick" : "fire",
			 "Blizzard" : "ice",
			 "Block" : "none",
			 "Blue Flare" : "fire",
			 "Body Slam" : "normal",
			 "Bolt Strike" : "electric",
			 "Bone Club" : "ground",
			 "Bone Rush" : "ground",
			 "Bonemerang" : "ground",
			 "Boomburst" : "normal",
			 "Bounce" : "flying",
			 "Brave Bird" : "flying",
			 "Brick Break" : "fighting",
			 "Brine" : "water",
			 "Bubble" : "water",
			 "Bubble Beam" : "water",
			 "Bug Bite" : "bug",
			 "Bug Buzz" : "bug",
			 "Bulk Up" : "none",
			 "Bulldoze" : "ground",
			 "Bullet Punch" : "steel",
			 "Bullet Seed" : "grass",
			 "Calm Mind" : "none",
			 "Camouflage" : "none",
			 "Captivate" : "none",
			 "Celebrate" : "none",
			 "Charge" : "none",
			 "Charge Beam" : "electric",
			 "Charm" : "none",
			 "Chatter" : "flying",
			 "Chip Away" : "normal",
			 "Circle Throw" : "fighting",
			 "Clamp" : "water",
			 "Clear Smog" : "poison",
			 "Close Combat" : "fighting",
			 "Coil" : "none",
			 "Comet Punch" : "normal",
			 "Confide" : "none",
			 "Confuse Ray" : "none",
			 "Confusion" : "psychic",
			 "Constrict" : "normal",
			 "Conversion" : "none",
			 "Conversion 2" : "none",
			 "Copycat" : "none",
			 "Cosmic Power" : "none",
			 "Cotton Guard" : "none",
			 "Cotton Spore" : "none",
			 "Counter" : "fighting",
			 "Covet" : "normal"
			 }